<a href="https://colab.research.google.com/github/Chaskins1115/MAT494/blob/main/1_2_Homeowrk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [2]:
# index
a = np.arange(10)
print(a)
print(a[-1])
print(a[1:3])
print(a[1:5:2])

[0 1 2 3 4 5 6 7 8 9]
9
[1 2]
[1 3]


In [3]:
# slice index
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
b = a[:2, 1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [4]:
# inversion
A = np.matrix([[1,0,0],
               [0,1,0],
               [0,0,1]])

B = np.matrix([[3,1],
               [1,3]])

print(A, '\n')
print(np.trace(A), '\n')
print(np.invert(A), '\n')

print(B, '\n')
print(np.trace(B), '\n')
print(np.invert(B))

[[1 0 0]
 [0 1 0]
 [0 0 1]] 

3 

[[-2 -1 -1]
 [-1 -2 -1]
 [-1 -1 -2]] 

[[3 1]
 [1 3]] 

6 

[[-4 -2]
 [-2 -4]]


In [5]:
# stacking
a=np.full((3,2),1.)
b=np.full((3,2),2.)
c=np.full((3,2),3.)

print('a=',a)
print('b=',b)
print('c=',c)

print('hstack=',np.hstack((a,b,c)))
print('vstack=',np.vstack((a,b,c)))

a= [[1. 1.]
 [1. 1.]
 [1. 1.]]
b= [[2. 2.]
 [2. 2.]
 [2. 2.]]
c= [[3. 3.]
 [3. 3.]
 [3. 3.]]
hstack= [[1. 1. 2. 2. 3. 3.]
 [1. 1. 2. 2. 3. 3.]
 [1. 1. 2. 2. 3. 3.]]
vstack= [[1. 1.]
 [1. 1.]
 [1. 1.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
