<a href="https://colab.research.google.com/github/Chaskins1115/MAT494/blob/main/3_7_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

3.7 Neural Networks TensorFlow 2

Here we provide a simple example of Neural Network using TensorFlow 2 with MNIST dataset.

Source:

https://www.tensorflow.org/tutorials/quickstart/beginner



In [1]:
import tensorflow as tf

1. Load and prepare the MNIST dataset

Reference:

https://www.tensorflow.org/api_docs/python/tf/keras/datasets/mnist/load_data

This is a dataset of 60,000 28x28 grayscale images of the 10 digits, along with a test set of 10,000 images. It is considered another classic dataset in machine learning area. The images are handwritings of English letters. Researchers are using it as a training set to build neural network models that would recognize human handwritings.

The dataset we import from tf.keras is not the original image set, but numerical matrix that transfromed from the images via certain kernels.

tf.keras.datasets.mnist.load_data() will return tuples of arrays:

x_train: uint8 NumPy array of grayscale image data with shapes (60000, 28, 28), containing the training data. Pixel values range from 0 to 255.

y_train: uint8 NumPy array of digit labels (integers in range 0-9) with shape (60000,) for the training data.

x_test: uint8 NumPy array of grayscale image data with shapes (10000, 28, 28), containing the test data. Pixel values range from 0 to 255.

y_test: uint8 NumPy array of digit labels (integers in range 0-9) with shape (10000,) for the test data.

In [2]:
# load the dataset
mnist = tf.keras.datasets.mnist

# convert the samples from integers to floating-point numbers
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


11490434/11490434 [==============================] - 0s 0us/step


2. Build the tf.keras.Sequential model by stacking layers.

Choose an optimizer and loss function for training:

In the cell below there are a few things that are happening, by utilizing numpy for each example the model returns as mentioned below a vector of "logits" or "log-odds" scores for each class.

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.92039216,  0.64521885, -0.0288277 ,  0.01648408, -0.41477263,
        -0.42636308, -0.29052866,  0.35942733, -0.33729422,  0.18805918]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.04103735, 0.19638827, 0.10008774, 0.1047272 , 0.06804044,
        0.06725637, 0.07704166, 0.14756992, 0.0735217 , 0.12432934]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.6992435

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2954 - accuracy: 0.9132
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1447 - accuracy: 0.9566
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1090 - accuracy: 0.9673
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0903 - accuracy: 0.9722
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0744 - accuracy: 0.9765


3. Evaluate the Model

The Model.evaluate method checks the models performance, usually on a "Validation-set" or "Test-set".

Lastly in the main output we see the probability model being exrpessed below in the following array.

In [ ]:


In [9]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0721 - accuracy: 0.9783 - 772ms/epoch - 2ms/step


[0.07208162546157837, 0.9782999753952026]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])



In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.0103456e-08, 5.5653965e-10, 6.7230685e-06, 4.0476659e-04,
        1.4196490e-12, 1.0251958e-06, 2.4521089e-13, 9.9955529e-01,
        4.0618860e-07, 3.1697604e-05],
       [4.3407573e-07, 1.0099352e-04, 9.9987841e-01, 1.9466926e-05,
        1.1494846e-14, 2.1012581e-09, 3.4482346e-07, 2.0758428e-13,
        1.9095188e-07, 8.0655480e-14],
       [6.9985283e-08, 9.9748397e-01, 1.3351921e-04, 6.3322864e-06,
        3.3415825e-05, 2.4471112e-06, 1.1903422e-05, 2.0345615e-03,
        2.9318631e-04, 4.6065088e-07],
       [9.9942410e-01, 1.0695755e-09, 2.9284567e-05, 2.7347298e-08,
        5.7927873e-06, 1.0919549e-06, 3.4468636e-04, 7.1423092e-05,
        1.6038026e-08, 1.2356053e-04],
       [2.7216452e-06, 1.0015634e-09, 4.4515755e-06, 7.5143261e-09,
        9.9878079e-01, 4.8190785e-08, 1.3429664e-07, 8.0313468e-05,
        1.5948866e-07, 1.1313405e-03]], dtype=float32)>

Copyright 2019 The TensorFlow Authors.

In [13]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.